#!/bin/bash
dependapt()
{
## Module that will examine system for dependencies!
if [ -f /usr/sbin/synaptic ]
   then
       echo "Synaptic was found"
       echo ""
       sleep 1
   else
       echo "Synaptic not found"
       echo ""
       sleep 1
       apt-get -y install synaptic
       echo "Finished installing Synaptic"
       echo ""
       sleep 1
fi
if [ -f /usr/bin/deborphan ]
   then
       echo "Deborphan found"
       echo ""
       sleep 1
   else
       echo "Deborphan not found"
       echo ""
       sleep 1
       apt-get -y install deborphan
       echo "Finished installing Deborphan"
       echo ""
       sleep 1
fi
if [ -f /usr/bin/notify-send ]
   then
       echo "Notification system found"
       echo ""
       sleep 1
   else
       echo "Notification system not found"
       echo ""
       sleep 1
       apt-get -y install libnotify-bin
       echo "Finished installing Notification system"
       echo ""
       sleep 1
fi
if [ -f /usr/bin/zenity ]
   then
       echo "Zenity UI system found"
       echo ""
       sleep 1
   else
       echo "Zenity UI system not found"
       echo ""
       sleep 1
       apt-get -y install zenity
       echo "Finished installing Zenity UI system"
       echo ""
       sleep 1
fi
if [ -f /usr/bin/update-manager ]
   then
       echo "Update Manager system found"
       echo ""
       sleep 1
   else
       echo "Update Manager not found"
       echo ""
       sleep 1
       apt-get -y install update-manager
       echo "Finished installing Update Manager"
       echo ""
       sleep 1
fi  
$NotifySystem "Modules are succesfully loaded"
}
