#!/bin/bash
#_____________________________________________________________________________________________________________________________________________________________________
#Name   : uCareSystem
#Licence: GPL2 (http://www.gnu.org/licenses/gpl.html)
#Author : Salih Emin
#Email  : salihemin (at) about.me 
#Date   : 25-06-2011 (first release 19-02-2009)
#Version: 0.9 (based on 2click-update 7.0)
#System : Ubuntu Linux
#WebSite: http://ucaresystem.blogspot.com
#Source Code: https://github.com/cerebrux/uCareSystem
#Description:
#This simple script will automaticaly refresh your packagelist, download updates (if there are any), install them, make some clean up, remove unnecessary packages and files and optimize your RAM
#_____________________________________________________________________________________________________________________________________________________________________


TEXTDOMAIN="uCareSystem"
TEXTDOMAINDIR="/usr/local/share/locale/"
Icon="modules/ucaresystemicon.png"

#Below are the messages that are used in 2clickUpdate
MessageIntro=$"System components will be updated"
WindowTitle=$"uCareSystem 0.9"
MessageProgressTitle=$"Optimizing packages"
MessageComplete=$"uCareSystem operations are now complete"
NotifySystem='notify-send -i '$Icon''
NotifyMessageA=$"System is now under maintenance..."
NotifyMessageB=$"System maintenace complete"
MessageUpdate=$"# \n Please wait, this can take some time.\n \n \n Downloading package list"
MessageUpgrade=$"# \n Please wait, this can take some time.\n \n \n Downloading and Installing package upgrades"
MessageAutoremove=$"# \n Please wait, this can take some time.\n \n \n Removing package that are no more needed"
MessageDeborphan=$"# \n Please wait, this can take some time.\n \n \n Deleting any remaining configuration files"
MessageAutoclean=$"# \n Please wait, this can take some time.\n \n \n Removing temporary files"
MessageClean=$"# \n Please wait, this can take some time.\n \n \n Freeing up some disk space"
MessageRamCleaned=$"Optimizing RAM memory"
MessageDependency=$"# \n Please wait, this can take some time.\n \n \n Collecting system information"

#Just a Window that informs you what will happen
:<<COMMENT
zenity --info \
       --title "$WindowTitle" \
       --width 100 \
       --window-icon=/ucaresystemicon.png \
       --text "$MessageIntro"

COMMENT
#Display a cool notification baloon
$NotifySystem "$NotifyMessageA"

#Loading Modules
source modules/depend_apt.module
source modules/smart_apt.module
source modules/re_apt.module 
source modules/autorem_apt.module
source modules/orphan_apt.module
source modules/autoclean_apt.module
source modules/clean_apt.module
source modules/ramclean_apt.module

(
#Kernel begins ---->
set -x
echo "10%" && \
#_________________________________________________________
echo "$MessageDependency"&& \
dependapt
echo "$MessageUpgrade"&& \
# Module loaded for retreving and installing new versions of your installed software and system libraries
reapt && \
echo "20%" && \
smartapt && \
echo "30%" && \
#_________________________________________________________
echo "$MessageAutoremove" && \
autoremapt && \
echo "45%" && \
# Module loaded for removing packages that were automatically installed to satisfy dependencies for some package and that are no more needed.
#_________________________________________________________
#
echo "$MessageDeborphan" && \
orphanapt && \
echo "60%" && \
# Module loaded for removing packages and configurations which are not required by any other package upon your system
#_________________________________________________________
#
echo "$MessageAutoclean" && \
autocleanapt && \
echo "75%" && \
# Module loaded for removing all stored archives in your cache for packages that are no longer in the repositories or that have a newer version in the 
# repositories.
#_________________________________________________________
#
echo "$MessageClean" && \
cleanapt && \
echo "85%" && \
# Module loaded for deleting from cache the downloaded packages to free up some space
#_________________________________________________________
#
$NotifySystem "$MessageRamCleaned"  && \
ramcleanapt && \
echo "99%" && \
# Module loaded for synchronizing data on disk with memory and then free pagecache, dentries and inodes from RAM
sleep 1
set +x
#<----- Kernel Ends
) | $(zenity --width 300 \
           --height 250 \
           --progress \
           --percentage=1 \
           --window-icon="$Icon" \
           --title "$WindowTitle | $MessageProgressTitle" \
           --text="System is being updated. Please be patient...." \
           --auto-close) 

#Display a cool notification baloon
$NotifySystem "$NotifyMessageB"

zenity --width 300 --info --window-icon= "modules/ucaresystemicon.png" --title "$WindowTitle" --text="$MessageComplete"
