#!/bin/bash -xv
#____________________________________________________________________________________________________________________________________________________________________
#Name   : 2clickUpdate
#Licence: GPL2 (http://www.gnu.org/licenses/gpl.html)
#Author : Salih Emin
#Email  : cerebrux.gr (at) gmail.com 
#Date   : 25-10-2010 (first release 19-02-2009)
#Version: 6.0
#System : Ubuntu Linux
#WebSite: http://www.cerebrux.net
#Source Code: https://launchpad.net/2clickupdate
#Description:
#This simple script will automaticaly refresh your packagelist, download updates (if there are any), install them, make some clean up, remove unnecessary packages and files and optimize your RAM
#_____________________________________________________________________________________________________________________________________________________________________
#
#The "uCareSystem.run" is the executable that runs the main "uKernel"
#_____________________________________________________________________________________________________________________________________________________________________
#Cheking if user has Admin rights
#-m "Input your Admin Password"
if ! gksu 'modules/uKernel' ; then
    zenity --error --text "Λάθος συνθηματικό ! \n \n \nΠαρακαλώ τρέξτε πάλι το uCareSystem με το σωτό συνθηματικό"
    exit 1
fi

