#!/bin/bash -xv
#____________________________________________________________________________________________________________________________________________________________________
#Name   : uCareSystem
#License: GPL2 (http://www.gnu.org/licenses/gpl.html)
#Author : Salih Emin
#Email  : salihemin (at) about.me 
#Date   : 25-06-2011 (first release 19-02-2009)
#Version: 0.9 (based on 2click-update 7.0)
#System : Ubuntu Linux
#Web Site: http://ucaresystem.blogspot.com
#Source Code: https://github.com/cerebrux/uCareSystem
#Description:
#This simple script will automatically refresh your package list, download updates (if there are any), install them, make some clean up, remove unnecessary packages and files and optimize your RAM
#_____________________________________________________________________________________________________________________________________________________________________
#
#The "uCareSystem.run" is the executable that runs the main "uKernel"
#_____________________________________________________________________________________________________________________________________________________________________
#Checking if user has Admin rights
#-m "Input your Admin Password"
if ! gksu 'modules/uKernel' ; then
    zenity --error --text "Wrong Password ! \n \n \nPlease run uCareSystem again with the correct password"
    exit 1
fi

