#!/usr/bin/pkexec /bin/bash
set -e
#
#
#_______________________________________________
#THIS IS THE Terminal Version of uCareSystem
#_______________________________________________
# Name   : uCareSystem
# License: GPL3 (http://www.gnu.org/licenses/gpl.html)
# Author : Salih Emin
# WebSite: http://utappia.org
# Email  : salih-(at)-utappia.org
# Date   : 05-09-2024 (first release 19-02-2009)
# Version: 24.09.05
# System : Ubuntu Linux and derivatives. With Deb, Snap or Flatpak. (Partial support for Debian and WSL2) 
# Description:
#This simple script will automatically refresh your package list, download and install
#updates (if there are any),
#remove any remaining packages and configuration files without interference.
#
## Script starts here

#Variables
DIST_CODENAME=$(lsb_release --codename | cut -f2)
DATE=(date +%F_%T)
UCARE_VERSION=(24.09.05)
USERNAME=$(logname 2>/dev/null || echo $USER)
PREV_VER=(24.07)
# Checking if the user has run the script with "sudo" or not
if [[ $EUID -ne 0 ]] ; then
    clear
    echo ""
    echo "uCareSystem must be run as root or with sudo."
    echo "Now I will just exit..." 1>&2
    echo ""
    sleep 2
    exit 1
fi
# Function to check internet connectivity
function CHECK_INTERNET {
    if curl -4 -s --head http://archive.ubuntu.com | head -n 1 | grep "200 OK" > /dev/null; then
        return 0  # Internet connection is available
    else
        return 1  # No internet connection
    fi
}
# Check internet connectivity
if ! CHECK_INTERNET; then
   echo "No internet connection detected... "
   sleep 1
   echo "Please ensure that your device is connected to the internet,"
   echo "and try again.... " 
   echo "Now I will just exit..."1>&2
   echo ""
   sleep 2
   exit 1
fi

# Simple countdown function
function COUNTDOWN {
    	secs=$1
	while [ $secs -gt 0 ]; do
		echo -ne "$MESSAGE in $secs seconds... (to stop the countdown Ctrl+C) \r"
		sleep 1
		: $((secs--))
	done
	
	}
duration=5 # countdown duration in seconds

function WELCOME_SCREEN {
	echo "_______________________________________________________"
	echo "                                                       "
	echo "            uCareSystem $UCARE_VERSION                 "
	echo "            ~~~~~~~~~~~~~~~~~~~~~                      "
	echo " Welcome to all-in-one System Update and maintenance   "
	echo " assistant app.                                        "
	echo "					 		     "
	echo " 		Dear $USERNAME 		                     "
	echo "                                                       "
	echo " If you've found it helpful and it has saved you time  "
	echo " please consider supporting its development with a     "
	echo " donation via PayPal. Your support not only fuels      "
	echo " continuous improvement but also inspires and          "
	echo " motivates me to keep pushing forward while also shows " 
	echo " your appreciation for the time and effort that I have "
	echo "               put into the project.                   "
	echo "           https://www.paypal.me/cerebrux              "
	echo "		  ____  ____  ____ 			     "
 	echo "		 / __ \/ __ \/ __ \			    "
	echo "		/ /_/ / /_/ / /_/ /			     "
    echo "		\____/\____/\____/			     "
    echo "		   / __ \/ __ \				     "
   	echo "		  / /_/ / /_/ / 			    "
    echo "  	  	  \____/\____/ 				     "
	echo "	In honor of the 2024 Olympic Games"
	echo "	Προς τιμήν της 33ης Ολυμπιάδας"
	echo "_______________________________________________________"
	echo
	# start the countdown
	MESSAGE="uCareSystem will start"
	COUNTDOWN $duration
}

function MAINTENANCE {
	echo
	echo
	echo "#########################"
	echo "          Started"
	echo "#########################"
	echo
	sleep 1
	echo
	echo "#######################################"
	echo "Checking Disk before System Maintenance"
	echo "#######################################"
	echo
	df_output=$(df -h / | awk 'NR==2 {print "Percentage of disk space used:", $5, "\nFree space available:", $4}')
	echo "Here is the disk space before cleaning"
	echo "$df_output"
	echo
	sleep 1

	## Updates package lists
	if command -v systemctl &> /dev/null; then
		echo "Reloading systemd manager configuration"
		echo 
		sudo systemctl daemon-reload
		echo 
	fi
	
	echo "Updating package lists..."
	echo
	sudo apt update;
	echo
	echo "###############################"
	echo "Finished updating package lists"
	echo "###############################"
	sleep 1

	## Updates packages and libraries
	sudo apt full-upgrade -y;
	echo
	echo "###############################################"
	echo "Finished updating packages and system libraries"
	echo "###############################################"
	sleep 1
	echo

	## Removes unneeded packages
	sudo sudo apt autoremove -y --purge;
	echo					
	echo "###################################"
	echo "Finished removing unneeded packages"
	echo "###################################"
	sleep 1
	echo
	echo "Checking for Snap and Flatpak updates and removing unused revisions..."
	echo
	# Check if Snap is installed
	if command -v snap &> /dev/null; then
	# Stop all running Snap applications
		echo "Stopping all running Snap applications..."
		stopped_snaps=()
		while IFS= read -r snapname; do
			if sudo snap stop "$snapname" &>/dev/null; then
				stopped_snaps+=("$snapname")
			fi
		done < <(sudo snap list | awk '/^name/ {next} {print $1}')

		# Print the names of stopped Snap applications
		if [ ${#stopped_snaps[@]} -gt 0 ]; then
			echo "Stopped Snap applications:"
			for snapname in "${stopped_snaps[@]}"; do
				echo "$snapname"
			done
			# Check for updates and install them
			echo "Checking for updates and installing them..."
			echo
			sudo snap refresh

			# Remove old revisions of Snap packages
			echo
			echo "Removing old revisions of Snap packages..."
			LANG=C sudo snap list --all | awk '/disabled/{print $1, $3}' | 
				while read snapname revision; do
					sudo snap remove --purge "$snapname" --revision="$revision"
				done

			echo "Old revisions of Snap packages removed successfully."
			sleep 1
			# Start previously stopped Snap applications
			echo
			echo "Starting previously stopped Snap applications..."
			for snapname in "${stopped_snaps[@]}"; do
				sudo snap start "$snapname" &>/dev/null
			done
		else
			echo "No Snap applications were stopped."
		fi

	else
		echo
		echo "Snap is not available on this system. Skipping."
		sleep 1
	fi
	# Check if flatpak is installed then start maintenance
	if command -v flatpak &>/dev/null; then
		echo "Updating Flatpak packages..."
		sleep 1
		sudo flatpak update -y
		echo
		echo "Removing unused Flatpak packages..."
		sudo flatpak uninstall --unused -y
		sleep 1
		echo    
	else
		echo
		echo "Flatpak is not available on this system. Skipping."
		sleep 1
	fi
	echo					
	echo "################################################"
	echo "Finished refreshing of Snap and Flatpak packages"
	echo "################################################"
	sleep 1
	echo

	# purge-old-kernels - remove old kernel packages
	#    Copyright (C) 2012 Dustin Kirkland <kirkland -(at)- ubuntu.com>
	#
	#    Authors: Dustin Kirkland <kirkland-(at)-ubuntu.com>
	#             Kees Cook <kees-(at)-ubuntu.com>
	#
	# NOTE: This script will ALWAYS keep the currently running kernel
	# NOTE: Default is to keep 2 more, user overrides with --keep N
	KEEP=2
	# NOTE: Any unrecognized option will be passed straight through to apt
	APT_OPTS=
	while [ ! -z "$1" ]; do
		case "$1" in
			--keep)
				# User specified the number of kernels to keep
				KEEP="$2"
				shift 2
			;;
			*)
				APT_OPTS="$APT_OPTS $1"
				shift 1
			;;
		esac
	done

	# Build our list of kernel packages to purge
	CANDIDATES=$(ls -tr /boot/vmlinuz-* | head -n -${KEEP} | grep -v "$(uname -r)$" | cut -d- -f2- | awk '{print "linux-image-" $0 " linux-headers-" $0}' )
	for c in $CANDIDATES; do
		dpkg-query -s "$c" >/dev/null 2>&1 && PURGE="$PURGE $c"
	done

	if [ -z "$PURGE" ]; then
		echo "No kernels are eligible for removal"
	fi

	sudo apt $APT_OPTS remove -y --purge $PURGE;

	echo
	echo "###################################"
	echo "Finished removing old kernels"
	echo "###################################"
	sleep 1
	echo
	## Removes unused config files
	sudo deborphan -n --find-config | xargs sudo apt autoremove -y --purge;
	echo
	echo "#####################################"
	echo "Finished removing unused config files"
	echo "#####################################"
	sleep 1
	echo

	## Removes package files that can no longer be downloaded and everything except
	# the lock file in /var/cache/apt/archives, including directories.
	sudo apt-get -y autoclean; sudo apt-get -y clean;
	echo
	echo "######################################"
	echo " Cleaned downloaded temporary packages"
	echo "######################################"
	echo
	sleep 1

	echo
	echo "#########################################"
	echo " Checking to see if a reboot is required "
	echo "#########################################"
	echo
	## Check to see if a reboot is required
	if [ -f /var/run/reboot-required ]; then
 		echo
  		echo "* * * * * * * * * * * * * * * * * *"
 		echo "* Dear $USERNAME                  *"
 		echo "* Consider rebooting your system  *"
  		echo "* to finish applying updates      *"
  		echo "* requested by the following      *"
		echo "* packages:			*"
  		echo
		if [ -f /var/run/reboot-required.pkgs ]; then
        	cat /var/run/reboot-required.pkgs | uniq
    	else
        	echo "Cannot find the list of packages... Skipping"
    	fi
		sleep 1
	else 
		echo
		echo "No reboot is required at this time"
		echo
	fi
	sleep 1
	echo
	echo "######################################"
	echo "Checking Disk after System Maintenance"
	echo "######################################"
	echo
	df_output=$(df -h / | awk 'NR==2 {print "Percentage of disk space used:", $5, "\nFree space available:", $4}')
	echo "$df_output"
	echo
	sleep 1

}

function UPGRADE_EOL_TO_NEXT {

	cp "/etc/apt/sources.list" "/etc/apt/sources.eol_${DATE}"
	cat <<EOT > /etc/apt/sources.list
deb http://old-releases.ubuntu.com/ubuntu/ $DIST_CODENAME main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ $DIST_CODENAME-updates main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ $DIST_CODENAME-security main restricted universe multiverse

EOT

sudo apt-get install update-manager-core
sudo apt-get -y dist-upgrade
sudo do-release-upgrade
}

function UPGRADE_TO_NEXT_RELEASE {
	sleep 1
	echo "##########################################"
	echo "uCareSystem will now check for the        "
	echo "availability of the next version          "
	echo "and it will start the upgrade             "
	echo "##########################################"
	echo ""
	sleep 1
	do-release-upgrade
	sleep 2
}

function UPGRADE_TO_DEVEL_RELEASE {
	sleep 1
	echo "##########################################"
	echo "uCareSystem will now check for the        "
	echo "availability of the next development      "
	echo "version and it will start the upgrade     "
	echo "##########################################"
	echo ""
	sleep 1
	do-release-upgrade -d
	sleep 2
}

function SHOW_HELP {
	cat << EOF
	
				     uCareSystem
				    ~ $UCARE_VERSION ~
		     All-in-one system update and maintenance app

	Usage: sudo ucaresystem-core <parameter> 
	
	If no parameter is specified, it will just do the regular
	maintenance:
	
	 * Updates the list of available packages
	 * Downloads and installs the available updates
	 * Checks if there are older Linux kernels on the system and removes
	   them. However it keeps the current and one previous version of 
	   the kernel.
	 * Cleans the cache of the downloaded packages
	 * Removes obsolete packages
	 * Removes orphan packets
	 * Deletes package configuration files from packages that have been
	   uninstalled by you.
	
	Parameter:	 
		 -h          display this help and exit
		 
		 -u          Upgrade to the next release. Note: If you use a
		             regular release it will upgrade to the next one. If
		             you are on a LTS version, it will upgrade only to 
		             the next LTS.
		             
		 -d          Upgrade to the next development release

		 -eol        CAUTION: Do not use this if your Ubuntu has not 
			     reached its End of life support.
				    Check https://wiki.ubuntu.com/Releases
			     This option is for Ubuntu releases that have
			     reached their EOL and the user wants to upgrade
			     it to the next supported version.
		 
		 -r          After completing all the tasks, reboot the system
		 
		 -s	     After completing all the tasks, shutdown the system

EOF
}

function GOODBYE {
	sleep 1
	echo "_______________________________________________________"
	echo "                                                       "
	echo "            uCareSystem $UCARE_VERSION                 "
	echo "            ~~~~~~~~~~~~~~~~~~~~~                      "
	echo "         				                     "
	echo " I am deeply grateful for your generous donations      "
	echo " during the $PREV_VER development cycle. Your contributions"
	echo " have been invaluable in helping me enhance and        "
	echo " maintain the project. Thank you for believing in this "
	echo " project and for being a crucial part of its success.  " 
	echo "		 					     "
	echo " Dear $USERNAME, the following names are the legneds   "
	echo " of $PREV_VER development cycle, supporters:				 "
	echo " 	E. Dennis, S. Slagle, M. Van Hoof, B. Breitfeld  "     
	echo "  Dom. Babic, L. Miller, St. Matsumoto, C. Quimbay  "
	echo "                       				     "	
	echo "	https://www.paypal.me/cerebrux  		     "
	echo "		  ____  ____  ____ 			     "
 	echo "		 / __ \/ __ \/ __ \			    "
	echo "		/ /_/ / /_/ / /_/ /			     "
    echo "		\____/\____/\____/			     "
    echo "		   / __ \/ __ \				     "
   	echo "		  / /_/ / /_/ / 			    "
    echo "  	  	  \____/\____/ 				     "
	echo "	In honor of the 2024 Olympic Games"
	echo "	Προς τιμήν της 33ης Ολυμπιάδας"
	echo "							     "
	echo "     	All maintenace Complete... GOODBYE	     "
	echo "_______________________________________________________"
	echo
}

function SHUT_DOWN {
	sleep 1
	echo
	echo
	echo "##############################"
	echo "Shutting down as you requested"
	echo "##############################"
	echo
	MESSAGE="Shuting down"
	COUNTDOWN $duration
	sudo shutdown now
}

function RE_BOOT {
	sleep 1
	echo
	echo
	echo "##########################"
	echo "Rebooting as you requested"
	echo "##########################"
	echo
	MESSAGE="Rebooting"
	COUNTDOWN $duration
	sudo reboot
	## End of script
}

# The main process starts
while [ "$1" != "" ]; do
    case $1 in
        -u | --upgrade )     WELCOME_SCREEN && MAINTENANCE && UPGRADE_TO_NEXT_RELEASE
                             exit
                                ;;
        -d | --development ) WELCOME_SCREEN && MAINTENANCE && UPGRADE_TO_DEVEL_RELEASE
                             exit
                                ;;
        -h | --help )        SHOW_HELP
                             exit
                                ;;
        -eol | --end-of-life-upgrade ) UPGRADE_EOL_TO_NEXT
                             exit
                                ;;
	-s | --shutdown )	 WELCOME_SCREEN && MAINTENANCE && GOODBYE && SHUT_DOWN
							 exit
							    ;;
	-r | --reboot )		 WELCOME_SCREEN && MAINTENANCE && GOODBYE && RE_BOOT
							 exit
							    ;;
        * )                  SHOW_HELP
                             exit 1
    esac
done
## If no parameter is given just do the regular maintenance
WELCOME_SCREEN && MAINTENANCE && GOODBYE
