.TH LAUNCH-UCARESYSTEMCORE 1 "April 2025" "uCareSystem" "uCareSystem Launcher"
.SH NAME
launch-ucaresystemcore \- launcher for uCareSystem Core
.SH SYNOPSIS
.B launch-ucaresystemcore
.SH DESCRIPTION
This is a launcher script for uCareSystem Core. It is not intended to be run directly.
.PP
This script launches \fBucaresystem-core\fR in a terminal window.
.SH SEE ALSO
.BR ucaresystem-core (1)
.SH AUTHOR
Salih Emin <salih-emin@ubuntu.com>
