.TH UCARESYSTEM-CORE "1" "July 2025" "ucaresystem-core" "User Commands"
.SH NAME
ucaresystem-core \- All-in-one system update and maintenance app
.SH DESCRIPTION
uCareSystem is an all-in-one system update and maintenance application.
.PP
Usage: sudo ucaresystem\-core <option>
.PP
If no option is specified, it performs the regular maintenance tasks.
It updates system, snap, and flatpak packages, removes old kernels, old
Snap and flatpack revisions and unneeded packages, and cleans up
configurations of uninstalled packages.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
Display version information and exit
.TP
\fB\-u\fR, \fB\-\-upgrade\fR
Upgrade to the next Ubuntu release. Note: If you use a
regular release it will upgrade to the next one. If
you are on a LTS version, it will upgrade ONLY to
the next LTS if it is available for upgrade.
.TP
\fB\-d\fR, \fB\-\-development\fR
Upgrade to the next development release of Ubuntu.
Note: This is only for testing purposes and it is not
recommended for production systems.
It will upgrade to the next development release, even
if you are on a regular release or LTS version.
Use with caution!
.TP
\fB\-eol\fR, \fB\-\-end\-of\-life\-upgrade\fR
CAUTION: Do not use this if your Ubuntu has not
reached its End of life support.
Check https://wiki.ubuntu.com/Releases
This option is ONLY for Ubuntu releases that have
reached their EOL and you want to upgrade
it to the next supported version.
.TP
\fB\-r\fR, \fB\-\-reboot\fR
Reboot the system, after completing all the tasks.
.TP
\fB\-s\fR, \fB\-\-shutdown\fR
Shutdown the system, after completing all the tasks.
.SH EXAMPLES
.TP
\fBucaresystem-core\fR
Perform regular system maintenance
.TP
\fBucaresystem-core --version\fR
Display version information
.TP
\fBucaresystem-core --upgrade\fR
Perform maintenance and upgrade to the next release
.SH SUPPORT
Support this project: <https://www.paypal.com/donate/?hosted_button_id=SATQ6Y9S3UCSG>
.SH REPORTING BUGS
Report bugs to <https://github.com/Utappia/uCareSystem/issues>
.SH AUTHOR
Salih Emin <salih-emin@ubuntu.com>