name: Build DEB Package

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  release:
    types: [published]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          devscripts \
          debhelper \
          dh-make \
          build-essential \
          lintian \
          fakeroot \
          dpkg-dev \
          git-buildpackage
    
    - name: Get version information
      id: version
      run: |
        if [ -f VERSION ]; then
          VERSION=$(cat VERSION)
        else
          VERSION=$(grep -o 'UCARE_VERSION="[^"]*"' src/ucaresystem-core | cut -d'"' -f2 || echo "1.0.0")
        fi
        
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "debian_version=$VERSION-1" >> $GITHUB_OUTPUT
        else
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          echo "version=$VERSION+git$COMMIT_SHORT" >> $GITHUB_OUTPUT
          echo "debian_version=$VERSION+git$COMMIT_SHORT-1" >> $GITHUB_OUTPUT
        fi
    
    - name: Update debian/changelog
      run: |
        export DEBEMAIL="salih-emin@ubuntu.com"
        export DEBFULLNAME="Salih Emin"
        
        dch --newversion "${{ steps.version.outputs.debian_version }}" \
            --distribution "unstable" \
            --urgency "medium" \
            "Automated build from commit ${{ github.sha }}"
    
    - name: Build package
      run: |
        dpkg-buildpackage -us -uc -b
    
    - name: Run lintian
      run: |
        lintian --info --display-info --display-experimental --pedantic ../ucaresystem-core_*.deb || true
    
    - name: List generated files
      run: |
        ls -la ../*.deb ../*.buildinfo ../*.changes || true
    
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: ucaresystem-deb-${{ steps.version.outputs.version }}
        path: |
          ../*.deb
          ../*.buildinfo
          ../*.changes
    
    - name: Upload to release (if release event)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ../ucaresystem-core_${{ steps.version.outputs.debian_version }}_all.deb
        asset_name: ucaresystem-core_${{ steps.version.outputs.debian_version }}_all.deb
        asset_content_type: application/vnd.debian.binary-package